### ISSUE TITLE
dataframe as input for perm.method = 'permD'

### ISSUE THREAD

**Issue by zh1peng** [ucsf-ferguson-lab/syndRomics#12]
Hi thank you for the toolbox and tutorial.
I spotted a tiny issue:
pca_data is set as a matrix in your tutorial, if use that as an input, permD method will give the following error, but it works well for permV method.
```
Error in UseMethod("tbl_vars") : 
  no applicable method for 'tbl_vars' applied to an object of class "c('matrix', 'double', 'numeric')" 
```

It can be fixed either by passing a dataframe (use `as.data.frame(pca_data)` instead of `pca_data` to the function or check and convert it before `mutat_all(.FUN=sample)` in the function `permut_pca_D.princals`

**Comment by ATEspin** [comment]
Hi @zh1peng

thanks for reporting the bug. I made the correction in the function in the latest push
