### ISSUE TITLE
CI for loadings and communalities plots not positioned properly

### ISSUE THREAD

**Issue by tk27182** [ucsf-ferguson-lab/syndRomics#6]
I've been playing with this package using the Ionosphere dataset and when I get to plotting the standardized loadings and communalities with barmaps, the confidence intervals are not located at the tips of the bars but seem to randomly be displaced.

The code I've written to produce the plots is below:

```
library(syndRomics)
library(ggplot2)
library(dplyr)
library(stringr)
library(mlbench)

# Load Johns Hopkins University Ionosphere dataset
data(Ionosphere)

# Remove columns for classification or that only have 1 unique value
idf <- Ionosphere[, !(names(Ionosphere) %in% c("V2", "Class"))]

# Create PCA
ipca_data <- as.matrix(apply(idf, 2, as.numeric))
ipca <- prcomp(ipca_data, center = T, scale. = T)

# Extract standardized loadings
iloadings <- stand_loadings(ipca, ipca_data)

# Permute and keep components
set.seed(500)
P <- 500
ndim <- 5
iper <- permut_pc_test(ipca, ipca_data, P = P, ndim = ndim, statistic = "VAF")

# Component Interpretation
is_per <- permut_pc_test(ipca, ipca_data, P=P, ndim=ndim, statistic='s.loadings', perm.method = 'permV')

# Component stability
ibooted_PCA <- pc_stability(ipca, ipca_data, ndim = ndim, B = P, similarity_metric = 'all')

# Plot loadings and CI
show(plot(ibooted_PCA, plot_resample = T))

# Plot communalities & CI
show(plot(ibooted_PCA, communalities = T, plot_resample = T))
```

![iono_loadings](https://user-images.githubusercontent.com/14067153/113346425-7311f200-92f9-11eb-9cd1-d6e7526a08ab.png)
![iono_commun](https://user-images.githubusercontent.com/14067153/113346427-73aa8880-92f9-11eb-96a0-71ade2408ff4.png)

Is there some way I can adjust the positions of the CI's?

**Comment by ATEspin** [comment]
There is a bug in the code that organizes the variables. I have a solution that is working. I will release a new version of the package soon as I get other bugs fixed. 

Thanks!
